"""Generate the static recognition catalog without importing the inference runtime."""

import argparse
import json
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "data/food_dataset/data.yaml"
OUTPUT = ROOT / "frontend/lib/generated/supportedFoods.ts"
DISPLAY_NAMES = {"veg_briyani": "Veg Biryani"}


def render_catalog(source: str) -> str:
    data = yaml.safe_load(source)
    if not isinstance(data, dict):
        raise ValueError("Dataset definition must be a mapping")
    names = data.get("names")
    if not isinstance(names, list) or not names:
        raise ValueError("names must be a nonempty ordered list")
    if type(data.get("nc")) is not int or data["nc"] != len(names):
        raise ValueError("nc must match the number of class labels")
    if any(not isinstance(name, str) or not name.strip() or name != name.strip() for name in names):
        raise ValueError("Class labels must be nonempty strings without surrounding whitespace")
    if len(set(names)) != len(names):
        raise ValueError("Class labels must be unique")
    catalog = [{"id": name, "name": DISPLAY_NAMES.get(name, name.replace("_", " ").title())} for name in names]
    return (
        "// Generated by scripts/generate_supported_foods.py; do not edit.\n"
        "// Model categories, not nutrition lookup aliases or a detection guarantee.\n"
        "export type SupportedFood = Readonly<{ id: string; name: string }>\n\n"
        "export const supportedFoods: readonly SupportedFood[] = "
        + json.dumps(catalog, indent=2, ensure_ascii=False)
        + "\n"
    )


def generate(source: Path = SOURCE, output: Path = OUTPUT, *, check: bool = False) -> None:
    expected = render_catalog(source.read_text(encoding="utf-8"))
    if check:
        if not output.is_file() or output.read_text(encoding="utf-8") != expected:
            raise ValueError("Supported-food catalog is stale or missing; run scripts/generate_supported_foods.py")
    else:
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(expected, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail on generated-file drift without writing")
    args = parser.parse_args()
    try:
        generate(check=args.check)
    except ValueError as error:
        parser.exit(1, f"{error}\n")
    print("Supported-food catalog checked" if args.check else "Supported-food catalog generated")
