"""Regenerate public contracts and policy; --check detects drift without writes."""
import argparse
import json
from pathlib import Path
import subprocess
import sys
import tempfile

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from backend.application import create_app
from backend.domain.policy import POLICY
from backend.domain.rules import NutritionRules
from backend.settings import Settings


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    schema = json.dumps(create_app(Settings()).openapi(), indent=2, ensure_ascii=False) + "\n"
    generated = "// Generated by scripts/generate_contracts.py. Do not edit.\nexport const nutritionPolicy = " + json.dumps(POLICY, indent=2, ensure_ascii=False) + " as const\n"
    rules = NutritionRules()
    fixtures = [{"goal": goal, "condition": condition, "calories": calories, "expected": rules.calculate_macros(goal, calories, condition)}
                for goal in POLICY["goals"] for condition in POLICY["conditions"] for calories in (500, 1500, 1800, 2000, 2500, 5000)]
    with tempfile.TemporaryDirectory() as directory:
        spec = Path(directory) / "openapi.json"
        spec.write_text(schema, encoding="utf-8")
        target = Path(directory) / "api.d.ts"
        subprocess.run(["node", str(ROOT / "frontend/node_modules/openapi-typescript/bin/cli.js"), str(spec), "--output", str(target)], check=True)
        outputs = {
            ROOT / "frontend/lib/generated/api.d.ts": target.read_text(encoding="utf-8"),
            ROOT / "frontend/lib/generated/nutritionPolicy.ts": generated,
            ROOT / "tests/contracts/openapi.json": schema,
            ROOT / "tests/contracts/macro-fixtures.json": json.dumps(fixtures, indent=2, ensure_ascii=False) + "\n",
        }
        for path, content in outputs.items():
            if args.check:
                if not path.exists() or path.read_text(encoding="utf-8") != content:
                    raise SystemExit(f"Generated file out of date: {path.relative_to(ROOT)}")
            else:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content, encoding="utf-8")
    print("Contracts and policy verified" if args.check else "Contracts and policy generated")


if __name__ == "__main__":
    main()
